# Namespace
namespace:
  create: true
  name: kai-school

# Deployment
replicaCount: 2

image:
  repository: mohamedazizbenhaha/hr-turnover-api
  tag: latest
  pullPolicy: Always

resources:
  requests:
    cpu: "300m"
    memory: "512Mi"
  limits:
    cpu: "600m"
    memory: "1024Mi"

securityContext:
  runAsNonRoot: true
  runAsUser: 1000

readinessProbe:
  httpGet:
    path: /predict
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 10

# Service
service:
  type: NodePort
  port: 5000
  nodePort: 30000

# Network Policy
networkPolicy:
  enabled: true
