apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-turnover-api
  namespace: {{ .Values.namespace.name }}
  labels:
    app: hr-turnover-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hr-turnover-api
  template:
    metadata:
      labels:
        app: hr-turnover-api
    spec:
      containers:
      - name: hr-turnover-api
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        securityContext:
          runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
          runAsUser: {{ .Values.securityContext.runAsUser }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.httpGet.path }}
            port: {{ .Values.readinessProbe.httpGet.port }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}