{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hr-turnover-api-network-policy
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector:
    matchLabels:
      app: hr-turnover-api
  policyTypes:
  - Ingress
  ingress:
  - from: []
    ports:
    - protocol: TCP
      port: 5000
{{- end }}