apiVersion: v1
kind: Service
metadata:
  name: hr-turnover-api-service
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: hr-turnover-api
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }}
  type: {{ .Values.service.type }}